try: update-expectations make-expectations-patch

diff --git a/taskcluster/kinds/update-expectations/kind.yml b/taskcluster/kinds/update-expectations/kind.yml
--- a/taskcluster/kinds/update-expectations/kind.yml
+++ b/taskcluster/kinds/update-expectations/kind.yml
@@ -15,6 +15,7 @@ task-defaults:
     docker-image: ghcr.io/eijebong/archipelago-yaml-checker:ci-141
     volumes:
       - /builds/worker/checkouts
+    taskcluster-proxy: true
   run-on-tasks-for: []
 
 kind-dependencies:
@@ -22,37 +23,49 @@ kind-dependencies:
 
 tasks:
   apworld:
-    description: Run archipelago test suite on an apworld
-    scopes:
-      by-tasks-for:
-        github-issue-comment: [github:create-comment:Eijebong/Archipelago-index]
-        default: []
+    description: Get new test expectations for an apworld
+    chained: true
     run:
       using: run-task
-      command: >-
-        cd $VCS_PATH &&
-        apwm download -i ./ -d /tmp/download -p "${TEST_APWORLD_NAME}:${TEST_APWORLD_VERSION}" &&
+      command: |-
+        set -e;
+
+        cd $VCS_PATH;
+        apwm download -i ./ -d /tmp/download -p "${TEST_APWORLD_NAME}:${TEST_APWORLD_VERSION}";
+        if [[ "${PREVIOUS_TASK}" != "" ]]; then
+          curl -SsL --compressed -v $(curl -SsL "${TASKCLUSTER_PROXY_URL}/queue/v1/task/${PREVIOUS_TASK}/artifact-content/public/test_results/${TEST_APWORLD_NAME}.toml" | jq -r .url) -o "/builds/worker/checkouts/vcs/meta/${TEST_APWORLD_NAME}.toml"
+          if [[ ! -s "/builds/worker/checkouts/vcs/meta/${TEST_APWORLD_NAME}.toml" ]]; then
+            rm "/builds/worker/checkouts/vcs/meta/${TEST_APWORLD_NAME}.toml"
+          fi
+        fi
+
+        set +e
+
         cd /ap/archipelago &&
         unshare -r -n uv run -n python3 -W ignore -O /ap/archipelago/ap_tests.py /ap/supported_worlds /tmp/download "${TEST_APWORLD_NAME}" ${TEST_APWORLD_VERSION} "${TEST_WORLD_NAME}" /builds/worker/checkouts/vcs/meta /builds/worker/test_results;
         export STATUS=$?;
-        [[ "STATUS" -ne "0" ]] &&
-        [[ "$NOTIFY" -eq "1" ]] &&
-        /usr/bin/curl --header "Content-Type: application/json" ${TASKCLUSTER_PROXY_URL}/github/v1/repository/Eijebong/Archipelago-index/issues/${GITHUB_PR}/comments --data "{\"body\": \"[Test failures for ${TEST_APWORLD_NAME}:${TEST_APWORLD_VERSION}](https://apdiff.bananium.fr/tests/${TASK_ID})\"}";
-        exit $STATUS
+        touch "/builds/worker/test_results/${TEST_APWORLD_NAME}";
+
+        # If status is 69; we had a fill error and we can't trust the results, exit with the proper code so it retries
+        if [[ $STATUS -eq 69 ]]; then
+          exit $STATUS
+        fi
+
+        # exit 0 if $STATUS != 0 and expectations changed.
+        # exit $STATUS otherwise as something must've gone very wrong
+
+
+        if [[ -s "/builds/worker/test_results/${TEST_APWORLD_NAME}.toml" ]]; then
+          exit 0
+        else
+          exit $STATUS
+        fi
     worker:
       retry-exit-status: [69]
       artifacts:
         - type: directory
           path: /builds/worker/test_results
           name: public/test_results
-      env:
-        by-tasks-for:
-          github-issue-comment:
-            NOTIFY: "1"
-          default:
-            NOTIFY: "0"
-    ap-deps:
-      - check
     dependencies:
       by-tasks-for:
         github-push: {}
